Layout/LineLength:
  Max: 100
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'
Style/MultilineBlockChain:
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/AbcSize:
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Exclude:
  - 'spec/**/*_spec.rb'
