require:
- rubocop-performance
- rubocop-rake
AllCops:
  Exclude:
  - 'lib/**/*_ui.rb'
Layout/LineLength:
  Max: 100
  # TODO: This is temporary
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'
  - 'Gemfile'
Style/MultilineBlockChain:
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/AbcSize:
  Max: 20
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Max: 15
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Style/AutoResourceCleanup:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/DateTime:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IpAddresses:
  Enabled: true
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
  - print
  - puts
  - warn
  - raise
  - require
  - require_relative
  - include
  Exclude:
  - Rakefile
  - 'spec/**/*_spec.rb'
Style/OptionHash:
  Enabled: true
Style/ReturnNil:
  Enabled: true
Style/StringHashKeys:
  Enabled: true
Style/StringMethods:
  Enabled: true
Lint/HeredocMethodCallPosition:
  Enabled: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/HeredocArgumentClosingParenthesis:
  Enabled: true
Lint/NumberConversion:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineAssignmentLayout:
  Enabled: true
