require: rubocop-performance
AllCops:
  Exclude:
  - 'lib/**/*_ui.rb'
Layout/LineLength:
  Max: 100
  # TODO: This is temporary
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'
Style/MultilineBlockChain:
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/AbcSize:
  Max: 20
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Max: 15
  Exclude:
  - 'spec/**/*_spec.rb'
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
