default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

common_production: &common_production
  <<: *default
  adapter: postgresql
  encoding: unicode

production:
  primary:
    <<: *common_production
    username: cube_trainer
    password: PjQaAYuGZ1ksUhTFvE4=
    database: cube_trainer
  global:
    <<: *common_production
    host: jaguar
    username: cube_trainer_global
    password: MxbgvXhHYKKMXfnCn30=
    database: cube_trainer_global
