name: Rubocop

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Update packages
      run: sudo apt update

    - name: Install Package Dependencies
      uses: mstksg/get-package@v1
      with:
        apt-get: libpq-dev yarn

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle config set without 'default doc job cable storage ujs test db'
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: bundle exec rubocop --parallel