name: Rubocop
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Install Bundler
      run: gem install bundler

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle config set without 'default development test production'
        bundle install --jobs 4 --retry 3

    - name: Run Rubocop
      run: bundle exec rubocop
