name: Rubocop
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install Bundler
      run: gem install bundler

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle config set without 'default development test production client'
        bundle install --jobs 4 --retry 3

    - name: Run Rubocop
      run: bundle exec rubocop
