name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update packages
      run: sudo apt update
    - name: Install Package Dependencies
      uses: mstksg/get-package@v1
      with:
        apt-get: libsqlite3-dev # libqt4-dev ruby-dev cmake
    - name: Install gem dependencies
      run: |
        gem install bundler
        bundle config set without 'ui'
        bundle install --jobs 4 --retry 3
    - name: Build and test with Rake
      run: |
        rails compile
	rails spec
