name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Qt
      uses: mstksg/get-package@v1
      with:
        apt-get:
        - libqt4-dev
        - build-essential
        - bison
        - openssl
        - libreadline5
        - libreadline-dev
        - curl
        - git-core
        - zlib1g
        - zlib1g-dev
        - libssl-dev
        - libsqlite3-0
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - autoconf
        - xorg-dev
        - libgl1-mesa-dev
        - libglu1-mesa-dev
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
