name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Package Dependencies
      uses: mstksg/get-package@v1
      with:
        apt-get: >
          libsqlite3-dev build-essential bison openssl libreadline5
          libreadline-dev git-core zlib1g zlib1g-dev libssl-dev vim
          libsqlite3-0 sqlite3 libqt4-dev
          libxml2-dev git-core subversion autoconf xorg-dev libgl1-mesa-dev
          libglu1-mesa-dev
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake uic
        bundle exec rake
