name: Typescript
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4.1.0
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Run npm ci (similar to install but made for CI)
      run: npm ci

    - name: Run Angular Build Prod
      run: npm run build

    - name: Run Angular Test
      run: npm run test_ci

    - name: Run Angular Lint
      run: npm run lint
