name: Typescript
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Install Bundler
      run: gem install bundler

    - name: Bundle install
      run: |
        bundle config set without 'default development test rubocop production'
        bundle install --jobs 4 --retry 3

    - name: Setup node
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
    
    - name: Run npm install
      run: bundle exec rake npm:install

    - name: Run Angular Build
      run: bundle exec rake ng:build

    - name: Run Angular Test
      run: bundle exec rake ng:test

    - name: Run Angular Lint
      run: bundle exec rake ng:lint
