name: Typescript
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Run npm install
      working-directory: client
      run: npm install

    - name: Run Angular Build
      working-directory: client
      run: PATH=$(npm bin):$PATH ng build

    - name: Run Angular Test
      working-directory: client
      run: PATH=$(npm bin):$PATH ng test

    - name: Run Angular Lint
      working-directory: client
      run: PATH=$(npm bin):$PATH ng lint
